/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teachrecmanagesys;
import panels.*;
/**
 *
 * @author Lenovo
 */
public class Dashboard extends javax.swing.JFrame {
    
    EducPanel educPanel = new EducPanel();
    Personal personalPanel = new Personal();
    Employment employmentPanel = new Employment();
    home home = new home();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        mainPanel.add(home);
        mainPanel.revalidate();  // Revalidate the panel to layout the added component
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        navigationPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnEduc1 = new javax.swing.JButton();
        btnEmployment = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        titleBar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 80, 1250, 720));

        navigationPanel.setBackground(new java.awt.Color(52, 73, 94));
        navigationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        navigationPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, -1));

        btnEduc1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnEduc1.setText("Educational Background");
        btnEduc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEduc1MouseClicked(evt);
            }
        });
        btnEduc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEduc1ActionPerformed(evt);
            }
        });
        navigationPanel.add(btnEduc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, -1));

        btnEmployment.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnEmployment.setText("Employment History");
        btnEmployment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmploymentMouseClicked(evt);
            }
        });
        btnEmployment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmploymentActionPerformed(evt);
            }
        });
        navigationPanel.add(btnEmployment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, -1));

        btnPersonal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnPersonal.setText("Personal Information");
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
        });
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });
        navigationPanel.add(btnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, -1));

        getContentPane().add(navigationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 720));

        titleBar.setBackground(new java.awt.Color(153, 153, 153));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Teachers Records Management System");
        titleBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();  // Clear existing components from the main panel
        mainPanel.add(home);     // Add the form to the main panel
        
        mainPanel.revalidate();  // Revalidate the panel to layout the added component
        mainPanel.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
       
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnEduc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEduc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEduc1MouseClicked

    private void btnEduc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEduc1ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();  // Clear existing components from the main panel
        mainPanel.add(educPanel);     // Add the form to the main panel
        
        mainPanel.revalidate();  // Revalidate the panel to layout the added component
        mainPanel.repaint();
    }//GEN-LAST:event_btnEduc1ActionPerformed

    private void btnEmploymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmploymentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmploymentMouseClicked

    private void btnEmploymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmploymentActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();  // Clear existing components from the main panel
        mainPanel.add(employmentPanel);     // Add the form to the main panel
        
        mainPanel.revalidate();  // Revalidate the panel to layout the added component
        mainPanel.repaint();
    }//GEN-LAST:event_btnEmploymentActionPerformed

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();  // Clear existing components from the main panel
        mainPanel.add(personalPanel);     // Add the form to the main panel
        
        mainPanel.revalidate();  // Revalidate the panel to layout the added component
        mainPanel.repaint();
    }//GEN-LAST:event_btnPersonalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEduc1;
    private javax.swing.JButton btnEmployment;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
