/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;




/**
 *
 * @author Lenovo
 */
public class home extends javax.swing.JPanel {
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }



    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblOverview2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTotalTeachers = new javax.swing.JLabel();
        nbTotalTeachers1 = new javax.swing.JLabel();
        lblOverview1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalTeachers1 = new javax.swing.JLabel();
        nbTotalTeachers2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTotalTeachers2 = new javax.swing.JLabel();
        nbTotalTeachers3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTotalTeachers3 = new javax.swing.JLabel();
        nbTotalTeachers = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Home");
        mainPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 50));

        lblOverview2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOverview2.setForeground(new java.awt.Color(23, 26, 31));
        lblOverview2.setText("Overview");
        mainPanel.add(lblOverview2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        summaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(summaryTable);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, 1250, 370));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTeachers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalTeachers.setForeground(new java.awt.Color(23, 26, 31));
        lblTotalTeachers.setText("Active SHS Teachers");
        jPanel1.add(lblTotalTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        nbTotalTeachers1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nbTotalTeachers1.setForeground(new java.awt.Color(23, 26, 31));
        nbTotalTeachers1.setText("0");
        jPanel1.add(nbTotalTeachers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, 60));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, 150));

        lblOverview1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOverview1.setForeground(new java.awt.Color(23, 26, 31));
        lblOverview1.setText("Summary Report");
        mainPanel.add(lblOverview1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTeachers1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalTeachers1.setForeground(new java.awt.Color(23, 26, 31));
        lblTotalTeachers1.setText("Resigned SHS Teachers");
        jPanel2.add(lblTotalTeachers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        nbTotalTeachers2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nbTotalTeachers2.setForeground(new java.awt.Color(23, 26, 31));
        nbTotalTeachers2.setText("0");
        jPanel2.add(nbTotalTeachers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 60));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 240, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTeachers2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalTeachers2.setForeground(new java.awt.Color(23, 26, 31));
        lblTotalTeachers2.setText("Retired SHS Teachers");
        jPanel3.add(lblTotalTeachers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        nbTotalTeachers3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nbTotalTeachers3.setForeground(new java.awt.Color(23, 26, 31));
        nbTotalTeachers3.setText("0");
        jPanel3.add(nbTotalTeachers3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, 60));

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 240, 150));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTeachers3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalTeachers3.setForeground(new java.awt.Color(23, 26, 31));
        lblTotalTeachers3.setText("Total SHS Teachers");
        jPanel4.add(lblTotalTeachers3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        nbTotalTeachers.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nbTotalTeachers.setForeground(new java.awt.Color(23, 26, 31));
        nbTotalTeachers.setText("0");
        jPanel4.add(nbTotalTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, 60));

        mainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 240, 150));

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOverview1;
    private javax.swing.JLabel lblOverview2;
    private javax.swing.JLabel lblTotalTeachers;
    private javax.swing.JLabel lblTotalTeachers1;
    private javax.swing.JLabel lblTotalTeachers2;
    private javax.swing.JLabel lblTotalTeachers3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nbTotalTeachers;
    private javax.swing.JLabel nbTotalTeachers1;
    private javax.swing.JLabel nbTotalTeachers2;
    private javax.swing.JLabel nbTotalTeachers3;
    private javax.swing.JTable summaryTable;
    // End of variables declaration//GEN-END:variables
}
