/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;
import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class Personal extends javax.swing.JPanel {
    
    
    
    ResultSet rs;
    Connection con;
    PreparedStatement ps;
    private String sql;
    
    String url = "jdbc:mysql://127.0.0.1:3306/terms";
    String user = "root";
    String password = "";
    
    private void checkEmployeeID() {
    try {
        con = DriverManager.getConnection(url, user, password);
        
            String query = "SELECT p.*, c.phone_number, c.lot_number, c.village, c.city, c.zip_code, " +
               "g.* " +
               "FROM personal_info p " +
               "LEFT JOIN contact_info c ON p.employeeID = c.employeeID " +
               "LEFT JOIN government_id g ON p.employeeID = g.employeeID " +
               "WHERE p.employeeID = ?";
        
        ps = con.prepareStatement(query);
        ps.setString(1, txtEmployeeID.getText());
        rs = ps.executeQuery();
        
        if (rs.next()) {
            System.out.println("✅ Data found for EmployeeID: " + txtEmployeeID.getText().trim());
            txtFirstName.setText(rs.getString("firstName"));
            txtMiddleName.setText(rs.getString("middleName"));
            txtLastName.setText(rs.getString("lastName"));
            java.sql.Date sqlDate = rs.getDate("birthday");
            int age = rs.getInt("age");
            txtAge.setText(String.valueOf(age));
            if (sqlDate != null) {
            LocalDate localDate = sqlDate.toLocalDate();
            txtBirthday.setDate(localDate);
        }else{
            txtBirthday.setDate(null);
            }
            
            String sex = rs.getString("sex");

            if ("Male".equalsIgnoreCase(sex)) {
            rbMale.setSelected(true);
            }           
            else if ("Female".equalsIgnoreCase(sex)) {
            rbFemale.setSelected(true);
            }

            String nationality = rs.getString("nationality");
            cbNationality.setSelectedItem(nationality);
            
            String civilStatus = rs.getString("civilStatus");
            cbCivilStatus.setSelectedItem(civilStatus);
            
            String religion = rs.getString("religion");
            cbReligion.setSelectedItem(religion);


            txtPhoneNumber.setText(rs.getString("phone_number"));
            txtLotNumber.setText(rs.getString("lot_number"));
            txtVillage.setText(rs.getString("village"));
            txtCity.setText(rs.getString("city"));
            txtZipCode.setText(rs.getString("zip_code"));
            
            txtPagIbig.setText(rs.getString("pagIbig"));
            txtPhilHealth.setText(rs.getString("philHealth"));
            txtTin.setText(rs.getString("tin"));
            txtGSIS.setText(rs.getString("gsis"));
            txtSSS.setText(rs.getString("sss"));

            btnProcess.setText("Update");
        } else {
            System.out.println("❌ No data found for EmployeeID: " + txtEmployeeID.getText().trim());
            erase();
        }

    } catch (SQLException ex) {
        Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    private void erase()
    {
        btnProcess.setText("Add");
        txtFirstName.setText(null);
        txtMiddleName.setText(null);
        txtLastName.setText(null);
        txtBirthday.setDate(null);
        txtAge.setText(null);
        bgSex.clearSelection();
        cbNationality.setSelectedIndex(-1);
        cbCivilStatus.setSelectedIndex(-1);
        cbReligion.setSelectedIndex(-1);
        txtPhoneNumber.setText(null);
        txtLotNumber.setText(null);
        txtVillage.setText(null);
        txtCity.setText(null);
        txtZipCode.setText(null);
        txtPagIbig.setText(null);
        txtPhilHealth.setText(null);
        txtTin.setText(null);
        txtGSIS.setText(null);
        txtSSS.setText(null);
    }

    /**
     * Creates new form Personal
     */
    public Personal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        cbReligion = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbNationality = new javax.swing.JComboBox<>();
        cbCivilStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFirstName4 = new javax.swing.JTextField();
        txtPhilHealth = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFirstName7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFirstName8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPagIbig = new javax.swing.JTextField();
        txtFirstName9 = new javax.swing.JTextField();
        txtFirstName10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtGSIS = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtSSS = new javax.swing.JTextField();
        txtTin = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtFirstName19 = new javax.swing.JTextField();
        txtLotNumber = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFirstName21 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtFirstName22 = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFirstName24 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtFirstName25 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtVillage = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtBirthday = new com.github.lgooddatepicker.components.DatePicker();
        txtMiddleName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        btnUpload = new javax.swing.JButton();
        txtEmployeeID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Middle Name:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 110, -1));

        jLabel4.setText("Last Name:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, -1));

        txtLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel5.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 210, 30));

        txtAge.setBackground(new java.awt.Color(255, 255, 255));
        txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel5.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 210, 30));

        jLabel5.setText("Birthday:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel6.setText("Sex:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel8.setText("First Name:");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, -1));

        txtFirstName.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel5.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 210, 30));

        cbReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Christian", "Islam", "Protestantism", "Iglesia Ni Cristo", "Aglipay", "Buddhism", "Hinduism" }));
        cbReligion.setBorder(null);
        cbReligion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbReligion.setInheritsPopupMenu(true);
        jPanel5.add(cbReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 210, 23));

        jLabel19.setText("Civil Status:");
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        cbNationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filipino", "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan", "Anguillan", "Argentine", "Armenian", "Australian", "Austrian", "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese", "Bermudian", "Bhutanese", "Bolivian", "Botswanan", "Brazilian", "British", "British Virgin Islander", "Bruneian", "Bulgarian", "Burkinan", "Burmese", "Burundian", "Cambodian", "Cameroonian", "Canadian", "Cape Verdean", "Cayman Islander", "Central African", "Chadian", "Chilean", "Chinese", "Citizen of Antigua and Barbuda", "Citizen of Bosnia and Herzegovina", "Citizen of Guinea-Bissau", "Citizen of Kiribati", "Citizen of Seychelles", "Citizen of the Dominican Republic", "Citizen of Vanuatu ", "Colombian", "Comoran", "Congolese (Congo)", "Congolese (DRC)", "Cook Islander", "Costa Rican", "Croatian", "Cuban", "Cymraes", "Cymro", "Cypriot", "Czech", "Danish", "Djiboutian", "Dominican", "Dutch", "East Timorese", "Ecuadorean", "Egyptian", "Emirati", "English", "Equatorial Guinean", "Eritrean", "Estonian", "Ethiopian", "Faroese", "Fijian", "Finnish", "French", "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Gibraltarian", "Greek", "Greenlandic", "Grenadian", "Guamanian", "Guatemalan", "Guinean", "Guyanese", "Haitian", "Honduran", "Hong Konger", "Hungarian", "Icelandic", "Indian", "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli", "Italian", "Ivorian", "Jamaican", "Japanese", "Jordanian", "Kazakh", "Kenyan", "Kittitian", "Kosovan", "Kuwaiti", "Kyrgyz", "Lao", "Latvian", "Lebanese", "Liberian", "Libyan", "Liechtenstein citizen", "Lithuanian", "Luxembourger", "Macanese", "Macedonian", "Malagasy", "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese", "Martiniquais", "Mauritanian", "Mauritian", "Mexican", "Micronesian", "Moldovan", "Monegasque", "Mongolian", "Montenegrin", "Montserratian", "Moroccan", "Mosotho", "Mozambican", "Namibian", "Nauruan", "Nepalese", "New Zealander", "Nicaraguan", "Nigerian", "Nigerien", "Niuean", "North Korean", "Northern Irish", "Norwegian", "Omani", "Pakistani", "Palauan", "Palestinian", "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Pitcairn Islander", "Polish", "Portuguese", "Prydeinig", "Puerto Rican", "Qatari", "Romanian", "Russian", "Rwandan", "Salvadorean", "Sammarinese", "Samoan", "Sao Tomean", "Saudi Arabian", "Scottish", "Senegalese", "Serbian", "Sierra Leonean", "Singaporean", "Slovak", "Slovenian", "Solomon Islander", "Somali", "South African", "South Korean", "South Sudanese", "Spanish", "Sri Lankan", "St Helenian", "St Lucian", "Stateless", "Sudanese", "Surinamese", "Swazi", "Swedish", "Swiss", "Syrian", "Taiwanese", "Tajik", "Tanzanian", "Thai", "Togolese", "Tongan", "Trinidadian", "Tristanian", "Tunisian", "Turkish", "Turkmen", "Turks and Caicos Islander", "Tuvaluan", "Ugandan", "Ukrainian", "Uruguayan", "Uzbek", "Vatican citizen", "Venezuelan", "Vietnamese", "Vincentian", "Wallisian", "Welsh", "Yemeni", "Zambian", "Zimbabwean" }));
        cbNationality.setBorder(null);
        cbNationality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbNationality.setInheritsPopupMenu(true);
        cbNationality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNationalityItemStateChanged(evt);
            }
        });
        cbNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNationalityActionPerformed(evt);
            }
        });
        jPanel5.add(cbNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 23));

        cbCivilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widowed" }));
        cbCivilStatus.setBorder(null);
        cbCivilStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbCivilStatus.setInheritsPopupMenu(true);
        cbCivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCivilStatusActionPerformed(evt);
            }
        });
        jPanel5.add(cbCivilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 210, 23));

        jLabel14.setText("Nationality:");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel20.setText("Religion:");
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Government ID's", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Home Address:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtFirstName4.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName4ActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 210, 23));

        txtPhilHealth.setBackground(new java.awt.Color(255, 255, 255));
        txtPhilHealth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPhilHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhilHealthActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhilHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pag-Ibig");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Phone Number:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtFirstName7.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName7ActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 23));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Phone Number:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtFirstName8.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName8ActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 23));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("PhilHealth");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        txtPagIbig.setBackground(new java.awt.Color(255, 255, 255));
        txtPagIbig.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPagIbig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagIbigActionPerformed(evt);
            }
        });
        jPanel3.add(txtPagIbig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 23));

        txtFirstName9.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFirstName9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName9ActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        txtFirstName10.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFirstName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName10ActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("GSIS");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 20));

        txtGSIS.setBackground(new java.awt.Color(255, 255, 255));
        txtGSIS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtGSIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGSISActionPerformed(evt);
            }
        });
        jPanel3.add(txtGSIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 23));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("SSS");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 20));

        txtSSS.setBackground(new java.awt.Color(255, 255, 255));
        txtSSS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSSActionPerformed(evt);
            }
        });
        jPanel3.add(txtSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 23));

        txtTin.setBackground(new java.awt.Color(255, 255, 255));
        txtTin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinActionPerformed(evt);
            }
        });
        jPanel3.add(txtTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 23));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tin");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 360, 300));

        jLabel7.setText("Age:");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        bgSex.add(rbMale);
        rbMale.setForeground(new java.awt.Color(0, 0, 0));
        rbMale.setText("Male");
        jPanel5.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 163, 70, 20));

        bgSex.add(rbFemale);
        rbFemale.setForeground(new java.awt.Color(0, 0, 0));
        rbFemale.setText("Female");
        jPanel5.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Contact Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Home Address:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtFirstName19.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName19ActionPerformed(evt);
            }
        });
        jPanel4.add(txtFirstName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 210, 23));

        txtLotNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtLotNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtLotNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLotNumberActionPerformed(evt);
            }
        });
        jPanel4.add(txtLotNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Phone Number:");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Phone Number:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtFirstName21.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName21ActionPerformed(evt);
            }
        });
        jPanel4.add(txtFirstName21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 23));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Phone Number:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtFirstName22.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName22ActionPerformed(evt);
            }
        });
        jPanel4.add(txtFirstName22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 23));

        txtPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtPhoneNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        jPanel4.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 23));

        txtFirstName24.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFirstName24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName24ActionPerformed(evt);
            }
        });
        jPanel4.add(txtFirstName24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("House/BlockLotNo.");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        txtFirstName25.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFirstName25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstName25ActionPerformed(evt);
            }
        });
        jPanel4.add(txtFirstName25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 23));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("City");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 20));

        txtCity.setBackground(new java.awt.Color(255, 255, 255));
        txtCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        jPanel4.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 23));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("ZIP code");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 20));

        txtZipCode.setBackground(new java.awt.Color(255, 255, 255));
        txtZipCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });
        jPanel4.add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 23));

        txtVillage.setBackground(new java.awt.Color(255, 255, 255));
        txtVillage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtVillage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVillageActionPerformed(evt);
            }
        });
        jPanel4.add(txtVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 23));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Subdivision/Village");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 360, 300));

        txtBirthday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtBirthday.setFocusable(false);
        jPanel5.add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 213, 30));

        txtMiddleName.setBackground(new java.awt.Color(255, 255, 255));
        txtMiddleName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleNameActionPerformed(evt);
            }
        });
        jPanel5.add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 210, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 890, 610));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setBackground(new java.awt.Color(255, 255, 255));
        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout photoLayout = new javax.swing.GroupLayout(photo);
        photo.setLayout(photoLayout);
        photoLayout.setHorizontalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photoLayout.setVerticalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 135, 180, 160));

        btnUpload.setText("Upload photo");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 305, 130, -1));

        txtEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmployeeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });
        txtEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployeeIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 385, 180, 23));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Employee ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 365, -1, -1));

        btnProcess.setText("Add");
        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProcess.setForeground(new java.awt.Color(0, 0, 0));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel2.add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 425, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 610));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Personal Information");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void cbNationalityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNationalityItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNationalityItemStateChanged

    private void cbNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNationalityActionPerformed

    private void cbCivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCivilStatusActionPerformed

    private void txtFirstName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName4ActionPerformed

    private void txtPhilHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhilHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhilHealthActionPerformed

    private void txtFirstName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName7ActionPerformed

    private void txtFirstName8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName8ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtEmployeeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIDKeyReleased
        checkEmployeeID();
    }//GEN-LAST:event_txtEmployeeIDKeyReleased

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        

        //Int Declarations
        int age;
        int phoneNumber;
        int lot;
        int zip;
        int pagIbig;
        int philHealth;
        int tin;
        int gsis;
        int sss;
        
        //String Declarations 
        String nationality = cbNationality.getSelectedItem().toString();
        String civilStatus = cbCivilStatus.getSelectedItem().toString();
        String religion = cbReligion.getSelectedItem().toString();
        
        String sex = "";
        if (rbMale.isSelected()) {
            sex = "Male";
        } else if (rbFemale.isSelected()) {
            sex = "Female";
        }
        
        //Contact info error handling
        try {
            age = Integer.parseInt(txtAge.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid age! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            phoneNumber = Integer.parseInt(txtPhoneNumber.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid phone number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            lot = Integer.parseInt(txtLotNumber.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid lot number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            zip = Integer.parseInt(txtZipCode.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid zip code! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            pagIbig = Integer.parseInt(txtPagIbig.getText()); // Convert only once
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid PAGIBIG number ! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            philHealth = Integer.parseInt(txtPhilHealth.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid PHILHEALTH number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            tin = Integer.parseInt(txtTin.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid TIN number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            gsis = Integer.parseInt(txtGSIS.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid GSIS number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        try {
            sss = Integer.parseInt(txtSSS.getText()); // Convert only once
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid SSS number! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        
        try {
            con=DriverManager.getConnection(url, user, password);
            
            LocalDate birthDate = txtBirthday.getDate(); 
            
            if (txtFirstName.getText().trim().isEmpty() ||
            txtMiddleName.getText().trim().isEmpty() ||
            txtLastName.getText().trim().isEmpty() ||
            txtAge.getText().trim().isEmpty() ||
            txtBirthday.getDate() == null ||
            sex.isEmpty() ||
            cbNationality.getSelectedItem() == null ||
            cbCivilStatus.getSelectedItem() == null ||
            cbReligion.getSelectedItem() == null ||
            txtPhoneNumber.getText().trim().isEmpty() ||
            txtLotNumber.getText().trim().isEmpty() ||
            txtVillage.getText().isEmpty() ||
            txtZipCode.getText().trim().isEmpty() ||
            txtPagIbig.getText().trim().isEmpty() ||
            txtPhilHealth.getText().trim().isEmpty() ||
            txtTin.getText().trim().isEmpty() ||
            txtGSIS.getText().trim().isEmpty() ||
            txtSSS.getText().trim().isEmpty())
            {
            JOptionPane.showMessageDialog(this, "Please fill up all information!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
            }
        
            java.sql.Date sqlDate = java.sql.Date.valueOf(birthDate);
             
            if(btnProcess.getText().equals("Add"))
            {
                sql = "INSERT INTO personal_info(employeeID, firstName, middleName, lastName, birthday, age, sex, nationality, civilStatus, religion) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                ps = con.prepareStatement(sql);
                ps.setString(1, txtEmployeeID.getText());
                ps.setString(2, txtFirstName.getText());
                ps.setString(3, txtMiddleName.getText());
                ps.setString(4, txtLastName.getText());
                ps.setDate(5, sqlDate);
                ps.setInt(6, age);
                ps.setString(7, sex);
                ps.setString(8, nationality);
                ps.setString(9, civilStatus);
                ps.setString(10, religion);
                ps.executeUpdate();
                
                sql = "INSERT INTO contact_info(employeeID, phone_number, lot_number, village, city, zip_code) VALUES ( ?, ?, ?, ?, ?, ?)";
                
                ps = con.prepareStatement(sql);
                ps.setString(1, txtEmployeeID.getText());
                ps.setInt(2, phoneNumber);
                ps.setInt(3, lot);
                ps.setString(4, txtVillage.getText());
                ps.setString(5, txtCity.getText());
                ps.setInt(6, zip);
                ps.executeUpdate();
                
                sql ="INSERT INTO government_id(employeeID, pagIbig, philHealth, tin, gsis, sss) VALUES ( ?, ?, ?, ?, ?, ?)";
                
                ps = con.prepareStatement(sql);
                ps.setString(1, txtEmployeeID.getText());
                ps.setInt(2, pagIbig);
                ps.setInt(3, philHealth);
                ps.setInt(4, tin);
                ps.setInt(5, gsis);
                ps.setInt(6, sss);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Successfully added to records!!");

            }
            else
            {
                sql = "UPDATE personal_info SET firstName = ?, middleName = ?, lastName = ?, birthday = ?, age = ?, sex = ?, nationality = ?, civilStatus = ?, religion = ? WHERE employeeID = ? ";
                
                ps = con.prepareStatement(sql);
                
                ps.setString(1, txtFirstName.getText());   
                ps.setString(2, txtMiddleName.getText());   
                ps.setString(3, txtLastName.getText());
                ps.setDate(4, sqlDate);
                ps.setInt(5, age);
                ps.setString(6, sex);
                ps.setString(7, nationality);
                ps.setString(8, civilStatus);
                ps.setString(9, religion);
                ps.setString(10, txtEmployeeID.getText());
                ps.executeUpdate();
                
                sql = "UPDATE contact_info SET phone_number = ? , lot_number = ?, village = ?, city = ?, zip_code = ? WHERE employeeID = ? ";
                
                ps = con.prepareStatement(sql);
                
                ps.setInt(1, phoneNumber);
                ps.setInt(2, lot);
                ps.setString(3, txtVillage.getText());
                ps.setString(4, txtCity.getText());
                ps.setInt(5, zip);
                ps.setString(6, txtEmployeeID.getText());
                ps.executeUpdate();
                
                sql = "UPDATE government_id SET pagIbig = ?, philHealth = ?, tin = ?, gsis = ?, sss = ? WHERE employeeID = ?";
                
                ps = con.prepareStatement(sql);
                
                ps.setInt(1, pagIbig);
                ps.setInt(2, philHealth);
                ps.setInt(3, tin);
                ps.setInt(4, gsis);
                ps.setInt(5, sss);
                ps.setString(6, txtEmployeeID.getText());
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Record Updated!!");
                
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btnProcessActionPerformed

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameFocusGained

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtPagIbigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagIbigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagIbigActionPerformed

    private void txtFirstName9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName9ActionPerformed

    private void txtFirstName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName10ActionPerformed

    private void txtGSISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGSISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGSISActionPerformed

    private void txtSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSSActionPerformed

    private void txtTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinActionPerformed

    private void txtFirstName19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName19ActionPerformed

    private void txtLotNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLotNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLotNumberActionPerformed

    private void txtFirstName21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName21ActionPerformed

    private void txtFirstName22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName22ActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtFirstName24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName24ActionPerformed

    private void txtFirstName25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstName25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstName25ActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtVillageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVillageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVillageActionPerformed

    private void txtMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleNameActionPerformed

    private void txtEmployeeIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSex;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cbCivilStatus;
    private javax.swing.JComboBox<String> cbNationality;
    private javax.swing.JComboBox<String> cbReligion;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel photo;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtAge;
    private com.github.lgooddatepicker.components.DatePicker txtBirthday;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFirstName10;
    private javax.swing.JTextField txtFirstName19;
    private javax.swing.JTextField txtFirstName21;
    private javax.swing.JTextField txtFirstName22;
    private javax.swing.JTextField txtFirstName24;
    private javax.swing.JTextField txtFirstName25;
    private javax.swing.JTextField txtFirstName4;
    private javax.swing.JTextField txtFirstName7;
    private javax.swing.JTextField txtFirstName8;
    private javax.swing.JTextField txtFirstName9;
    private javax.swing.JTextField txtGSIS;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLotNumber;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtPagIbig;
    private javax.swing.JTextField txtPhilHealth;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSS;
    private javax.swing.JTextField txtTin;
    private javax.swing.JTextField txtVillage;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
